In [1]:
import pandas as pd
import numpy as np

In [2]:
metadata_df = pd.read_csv("Image_Data/metadata.csv")

In [13]:
metadata_df.head(15)

,Record ID,File Name,Assignment ID,Year,Person,Keywords,Creators,Date
0,207431327,HearstTransportation_CAMP_MontrealTeam.png,CPR6931p,NaN,Unidentified,"People @ Work,Hearst transportation,Transporta...",NaN,NaN
1,207431332,HearstTransportation_MicrosoftTeams_ZoomMeetin...,CPR6931p,NaN,"Unidentified,Don Dickson,Danya Bynoe,Varun Kum...","People @ Work,Hearst transportation,Transporta...",NaN,NaN
2,207431348,HearstTransportation_BlackBook_LauraWehunt_1.png,CPR6931p,NaN,Laura Wehunt,"People @ Work,Hearst transportation,Headshots,...",NaN,NaN
3,207431356,HearstTransportation_BlackBook_LauraWehunt_2.png,CPR6931p,NaN,Laura Wehunt,"People @ Work,Hearst transportation,Headshots,...",NaN,NaN
4,207432753,HearstMagazines_CDS_Employee.png,CPR6931p,NaN,Bryan Phillips,"People @ Work,CDS,Hearst Magazines,Hearst maga...",NaN,NaN
5,207432784,HearstMagazines_Affinity Groups.png,CPR6931p,NaN,Unidentified,"People @ Work,Hearst Magazines,Hearst magazine...",NaN,NaN
6,207432786,HearstMagazines_Value_WeEvolveWithPurpose.png,CPR6931p,NaN,NaN,"People @ Work,Hearst Magazines,Hearst magazine...",NaN,NaN
7,207432788,HearstMagazines_Value_hearst_galleries.png,CPR6931p,NaN,Unidentified,"People @ Work,Hearst Magazines,Hearst magazine...",NaN,NaN
8,207432796,HearstMagazines_CommunityOutreach.png,CPR6931p,NaN,"Unidentified,Paul Luthringer,Stephanie Mayne,A...","People @ Work,Hearst Magazines,Hearst magazine...",NaN,NaN
9,207432797,HearstMagazines_HR_Good HousekeepingOffice.png,CPR6931p,NaN,Lauren Matthews,"People @ Work,Hearst Magazines,Hearst magazine...",NaN,NaN
10,207432881,HearstHealth_FDB_OneWarmCoat.png,CPR6931p,NaN,Unidentified,"People @ Work,FDB,Employee Image,Hearst Health...",NaN,NaN
11,207432894,HearstHealth_FDB_GivesBack3.png,CPR6931p,NaN,Unidentified,"People @ Work,FDB,Employee Image,Hearst Health...",NaN,NaN
12,207432937,HearstHealth_Executive.png,CPR6931p,NaN,Unidentified,"People @ Work,Employee Image,Hearst Health,Car...",NaN,NaN
13,207432942,HearstHealth_HCHB_Nurses_FromWebsite.png,CPR6931p,NaN,Unidentified,"People @ Work,Homecare Homebase,HCHB,Employee ...",NaN,NaN
14,207432947,HearstHealth_Clinical.png,CPR6931p,NaN,Unidentified,"People @ Work,Employee Image,Hearst Health,Car...",NaN,NaN

In [14]:
metadata_df.groupby(by = ['Keywords']).agg('count').sort_values(by = ['Record ID'], ascending=False)

,Record ID,File Name,Assignment ID,Year,Person,Creators,Date
Keywords,,,,,,,
"People @ Work,Homecoming,2013,Events,44th Floor,The Long Gray Line",443,443,443,443,416,0,0
"People @ Work,2018,Events,Friday,Texas,Texas 2018,Retreat",258,258,258,258,186,162,0
"Archdiocese of New York,Corporate,Al Smith Dinner 2021,2021,Al Smith Dinner,Alfred E. Smith Memorial Foundation,Alfred E. Smith Memorial Foundation Dinner,Charities,Executives,Events,Dinners,Catholic charities",230,230,0,230,230,230,0
"People @ Work,Spotlight 2016,Awards,Hearst Magazines,2016,Events,Spotlight,Magazines,44th Floor",140,140,0,140,129,1,0
"People @ Work,Frank A. Bennack,Frank Bennack,Events,FAB,2013,Homecoming,44th Floor,The Long Gray Line",127,127,127,127,127,68,0
...,...,...,...,...,...,...,...
"HearstLab Scouts,Clemente,Michelle Clemente,Hearst.com,Headshots,Portraits,2021,HearstLab,Scouts",1,1,1,1,1,1,0
"Hearst.com,Tiles,Headshots,Philips,1276x960,Portraits,HearstLab,Scouts,Cards,Emily Philips",1,1,1,1,1,1,0
"Hearst.com,Tiles,Headshots,Neal,1276x960,Portraits,Ginger Neal,HearstLab,Scouts,Cards",1,1,1,1,1,1,0
"Hearst.com,Headshots,Rob Barrett,Hearst Newspapers,Newspapers,Portraits,Bio Images",1,1,0,1,1,1,0
"Portraits,THE CLUB,Headshots,Portraits,2020",1,1,1,1,1,0,0

#### Split on comma and find individual keywords

In [5]:
clean_df = metadata_df.copy()

In [6]:
#Defining a dictionary 
keyword_dict = {}

split_df = clean_df['Keywords'].str.split(',',expand = True)
split_df

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,People @ Work,Hearst transportation,Transportation,Employee Image,CAMP,Hearst Transportation,Career Site,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,People @ Work,Hearst transportation,Transportation,Zoom,Employee Image,Hearst Transportation,Career Site,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,People @ Work,Hearst transportation,Headshots,Transportation,Black Book,Portraits,Employee Image,Hearst Transportation,Career Site,None,...,None,None,None,None,None,None,None,None,None,None
3,People @ Work,Hearst transportation,Headshots,Transportation,Black Book,Portraits,Employee Image,Hearst Transportation,Career Site,None,...,None,None,None,None,None,None,None,None,None,None
4,People @ Work,CDS,Hearst Magazines,Hearst magazines,Headshots,Magazines,Portraits,Employee Image,Career Site,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9294,Steven R. Swartz,Steve Swartz,SRS,Headshots,Portraits,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9295,Steven R. Swartz,Steve Swartz,SRS,Headshots,Portraits,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9296,Steven R. Swartz,Steve Swartz,SRS,Headshots,Portraits,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9297,Steven R. Swartz,Steve Swartz,125,SRS,Newseum,125th Anniversary,Citizen Hearst,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9298,Steven R. Swartz,Steve Swartz,SRS,Headshots,Portraits,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [7]:
split_df.values

array([['People @ Work', 'Hearst transportation', 'Transportation', ...,
        None, None, None],
       ['People @ Work', 'Hearst transportation', 'Transportation', ...,
        None, None, None],
       ['People @ Work', 'Hearst transportation', 'Headshots', ..., None,
        None, None],
       ...,
       ['Steven R. Swartz', 'Steve Swartz', 'SRS', ..., None, None, None],
       ['Steven R. Swartz', 'Steve Swartz', '125', ..., None, None, None],
       ['Steven R. Swartz', 'Steve Swartz', 'SRS', ..., None, None, None]],
      dtype=object)

In [10]:
id_df = pd.read_csv("Image_Data/ids.csv")

In [11]:
id_df = id_df.iloc[:,:2]

In [12]:
id_df[id_df['record_id'] == 207386272]

      record_id                    file_name
8175  207386272  Miller_cropped_PMC_3098.jpg

In [ ]:
df

In [ ]:
### Further steps